name: Cypress Test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Cypress Test
      uses: cypress-io/github-action@v5
      with:
        command: npx cypress run
        browser: chrome

    - name: Upload Reports
      uses: actions/upload-artifact@v3
      with:
       name: HTML Report
       path: cypressTestReport.html
